<div class="alert alert-block alert-info" align="center" style="padding: 10px;">
<h1><b><u>Basic Numpy</u></b></h1>
</div>

#### **Consider the below code to answer further questions:** ####

```python
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
```

---
#### **Q1. Is there any difference in the data type of variables list_ and array_list? If there is, then write code to print the data types of both the variables.** ####

Yes, there is a difference in the data type of the `list_` and `array_list` variables.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


---
#### **Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.** ####

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Data types of elements in list_
print("Data types of elements in list_:")
for i in list_:
    print(type(i))

# Data types of elements in array_list
print("\nData types of elements in array_list:")
for i in array_list:
    print(type(i))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


---
#### **Q3. Considering the following changes in the variable, array_list:** ####

```python
array_list = np.array(object=list_, dtype=int)
```

*Will there be any difference in the data type of the elements present in both the variables, `list_` and `array_list`? If so, then print the data types of each and every element present in both the variables, `list_` and `array_list`.*

**Answer:** Yes, there will be a difference in the data type of the elements present in the variables list_ and  array_list after specifying the dtype parameter as int.**

---
---

#### **Consider the below code to answer further questions:** ####
```python
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```
---
#### **Q4. Write a code to find the following characteristics of variable, num_array:** ####
    
- shape
- size

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) shape of num_array
shape = num_array.shape

# (ii) size of num_array
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


---
#### **Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.** ####

In [5]:
import numpy as np

# Create a 3x3 NumPy array with zeros
zeros_array = np.zeros((3, 3))

print("Shape of zeros_array:", zeros_array.shape)
print("Size of zeros_array:", zeros_array.size)

Shape of zeros_array: (3, 3)
Size of zeros_array: 9


---
#### **Q6. Create an identity matrix of shape (5,5) using numpy functions?** ####

In [6]:
import numpy as np

# Create a 5x5 NumPy array with zeros
zeros_array = np.eye(5)
print(zeros_array)
print("Shape of zeros_array:", zeros_array.shape)
print("Size of zeros_array:", zeros_array.size)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape of zeros_array: (5, 5)
Size of zeros_array: 25
